blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.ArticleListView.as_view(), name='article-list'),
    path('<int:id>/', views.ArticleDetailView.as_view(), name='article-detail'), #or use int:pk for default
    path('create/', views.ArticleCreateView.as_view(), name='article-create'),
    path('<int:id>/update/', views.ArticleUpdateView.as_view(), name='article-update'),
    path('<int:id>/delete/', views.ArticleDeleteView.as_view(), name='article-delete'),
]

djangotutorial/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('blog/', include('blog.urls'))
]

homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
    path('', views.index, name='index'),
    path('library/', views.library, name='library'),
    path('itemlist/', views.itemlist, name='itemlist'),
    path('create_item/', views.item_create_view, name='createitem'),
    path('item/<int:id>/', views.item_desc, name='itemdesc'),
    path('item/<int:id>/delete/', views.item_delete, name='itemdelete'),
    path('test_template/', views.testing_templates, name='testtemplate'),
]

homepage/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
# ref : https://docs.djangoproject.com/en/3.1/topics/db/models/
class Item(models.Model):
    name = models.CharField(max_length=100) # max_length = required
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=100000000)
    summary = models.TextField(blank=False, null=False)
    featured = models.BooleanField(default=False) #null=True, default=True

    def get_absolute_url(self):
        # return f"/item/{self.id}/"
        return reverse("homepage:itemdesc", kwargs={"id": self.id})

homepage/forms.py
from django import forms

from .models import Item

class ItemForm(forms.ModelForm):
    name = forms.CharField(widget=forms.Textarea(attrs={"placeholder": "your name", "rows": 1}))
    email = forms.EmailField()
    description = forms.CharField(required=False, widget=forms.Textarea(
                                                            attrs={
                                                                "placeholder": "your description",
                                                                "class": "new-class-name two",
                                                                "id": "my-id-for-textarea",
                                                                "rows": 15,
                                                                "cols": 100,
                                                            }
                                                        )
                                                    )
    price = forms.DecimalField(initial=199.99)
    class Meta:
        model = Item
        fields = [
            'name',
            'description',
            'price'
        ]
    
    def clean_name(self, *args, **kwargs):
        name = self.cleaned_data.get("name")
        # mengecek apakah ada string "item" di nama Item
        if not "item" in name:
            raise forms.ValidationError("This is not a valid name")
        return name
    
    def clean_email(self, *args, **kwargs):
        email = self.cleaned_data.get("email")
        # mengecek apakah ada string "item" di nama Item
        if not email.endswith("@gmail.com"):
            raise forms.ValidationError("This is not a valid email")
        return email
            




# ref: https://docs.djangoproject.com/en/3.1/ref/forms/fields/
class RawItemForm(forms.Form):
    name        = forms.CharField(label='', widget=forms.Textarea(attrs={"placeholder": "your name"}))
    description = forms.CharField(required=False, widget=forms.Textarea(
                                                            attrs={
                                                                "placeholder": "your description",
                                                                "class": "new-class-name two",
                                                                "id": "my-id-for-textarea",
                                                                "rows": 15,
                                                                "cols": 100,
                                                            }
                                                        )
                                                    )
    price       = forms.DecimalField(initial=199.99) 

homepage/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404, redirect
from django.http import Http404
from .models import Item
from .forms import ItemForm, RawItemForm

# Create your views here.
# def authenticate_user(request):
#     if request.user.is_authenticated():
        

def index(request):
    dummy = {
        "animal": "doggy",
        "weapon": "glock",
        "health": 1000,
    }
    # return render(request, 'index.html', {})
    return render(request, 'index.html', dummy)

def library(request):
    books = {
        "history": ["1945", "9/11", "Tiananmen Square"],
        "geography": ["earth before pearl harbor", "Asia"],
        "chinese_cartoon": ["Naburo", "SAsaske"],
        "codes": [123,537,69,210,432],
        "test_html": "<h3>This is just a normal header 3 text</h3>"
    }
    # return render(request, 'index.html', {})
    return render(request, 'library.html', books)

def itemlist(request):
    # ref : https://stackoverflow.com/questions/3090302/how-do-i-get-the-object-if-it-exists-or-none-if-it-does-not-exist
    query_set = Item.objects.all()
    data = {
        # "name": obj.name,
        # "description": obj.description,
        # "price": obj.price
        "item_list": query_set
        }
    return render(request, 'itemlist.html', data)

#forms for item with django modelforms (automatic)
def item_create_view(request):
    form = ItemForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = ItemForm()

    context = {
        'form': form
    }
    return render(request, 'create_item.html', context)

def item_desc(request, id):
    # obj = Item.objects.get(id=id)
    #if you want to avoid DoesNotExist
    #use try except and raise Http404 or
    # obj = Item.objects.filter(id=id).first() #ref:https://stackoverflow.com/a/3090342
    #or
    obj = get_object_or_404(Item, id=id)
    context = {
        "object" : obj
    }
    return render(request, "item.html", context)

#forms for item with django forms (manual/raw)
# def item_create_view(request):
#     my_form = RawItemForm()
#     if request.method == "POST":
#         my_form = RawItemForm(request.POST)
#         if my_form.is_valid():
#             #now the data is good
#             print(my_form.cleaned_data) #for testing
#             Item.objects.create(**my_form.cleaned_data)
#         else:
#             print(my_form.errors) #for testing
#     context = {
#         'form': my_form 
#     }
#     return render(request, 'create_item.html', context)

def item_delete(request, id):
    # obj = Item.objects.get(id=id)
    #if you want to avoid DoesNotExist
    #use try except and raise Http404 or
    # obj = Item.objects.filter(id=id).first() #ref:https://stackoverflow.com/a/3090342
    #or
    obj = get_object_or_404(Item, id=id)
    if request.method == "POST":
        #confirming delete
        obj.delete()
        return redirect('../../../itemlist/') 
    context = {
        "object" : obj
    }
    return render(request, "item_delete.html", context)

def testing_templates(request):
    return render(request, "test_template.html")

homepage/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'homepage.css' %}">
    <title>Django Test</title>
</head>
<body>
    {% include 'navbar.html' %}
    {% block content %}
    {% endblock %}
</body>
</html>

homepage/templates/create_item.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2>Create item here</h2>

<form action='.' method='POST'> {% csrf_token %}
{{ form.as_p }}
<input type='submit' value='Save' /> 
</form>

{% endblock %}

homepage/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Test</h1>
    <p>test 1 2 3 ...</p>
    <p>user :{{ user.first_name }}</p>
    <p>email :{{ user.email }}</p>
    <p>is authenticated:{{ user.is_authenticated }}</p>
    <p>animal: {{ animal }}</p>
    <p>weapon: {{ weapon }}</p>
    <p>health: {{ health }}</p>
    <br>
    <img src="{% static 'dog.jpg' %}" width="100px" height="100px">

    <!-- <a href="{% url 'homepage:index' %}">...</a> -->
{% endblock %}

homepage/templates/item.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h3>Item</h3>
<p>id : {{ object.id }}</p>
<p>name : {{ object.name }}</p>
{% if object.description is not None %}
    <p>description : {{ object.description }}</p> 
{% else %}
    <p>coming soon</p>
{% endif %}
<p>price : {{ object.price }}</p>
<br>
<a href="../../item/{{ object.id }}/delete/">Delete Item</a>

{% endblock %}

homepage/templates/item_delete.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<form action="." method="POST">{% csrf_token %}
    <h1>Are you sure you want to delete the item {{ object.name }}???</h1>
    <p><input type="submit" value="Yes" /> 
        <br>
        <a href="../">Cancel</a>
    </p>
</form>


{% endblock %}

homepage/templates/itemlist.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h3>Item List</h3>

{% for instance in item_list %}
    <p>{{ instance.id }} -- {{ instance.name }}</p>
    <p>{{ instance.description }}</p>
    <p>{{ instance.price }}</p>
    <p><a href="{{ instance.get_absolute_url }}">Item page</a></p>

{% endfor %}

{% endblock %}

homepage/templates/library.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <h1>Library</h1>
    <h3>sssshhh...</h3>
    <br>
    <br>
    <h4>List of books:</h4>
    <p>History :</p>
    <ul>
    {% for books in history %}
        <li>{{ books }}</li>
    {% endfor %}
    </ul>
    <br>
    <p>Geography</p>
    <ul>
    {% for books in geography %}
        <li>{{ forloop.counter }} - {{ books }}</li>
    {% endfor %}
    </ul>
    <br>
    <p>Chinese Cartoon</p>
    <ul>
    {% for books in chinese_cartoon %}
        <li>{{ books }}</li>
    {% endfor %}
    </ul>
    <br>
    <p>Number of available room</p>
    <ul>
    {% for num in codes %}
        {% if num == 69 %}
            <li>{{ num|add:69351 }} noice...</li>
        {% else %}
            <li>{{ num }}</li>
        {% endif %}
    {% endfor %}
    </ul>
    <br>
    {{ test_html|safe }}
    {{ test_html|striptags }}
    <br>
    <p>ref for built in templates : https://docs.djangoproject.com/en/3.1/ref/templates/builtins/</p>

{% endblock %}

homepage/templates/navbar.html
<nav>
    <ul>
        <li><a href="{% url 'homepage:index' %}"> Home </a></li>
        <li><a href="{% url 'homepage:library' %}"> Library </a></li>
        <li><a href="{% url 'homepage:itemlist' %}"> Items </a></li>
        <li><a href="{% url 'homepage:createitem' %}"> Create Item </a></li>
        <li><a href="{% url 'blog:article-list' %}"> Create Item </a></li>
        <li>Enemy</li>
    </ul>
</nav>